name: lint

on:
  push:
    branches:
      - "*"
    paths:
      - "*.py"

jobs:
    flake8_py3:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv wheel 
      
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Install flake8
        run: pipenv install flake8

      - name: Run flake8
        run: pipenv run flake8
