name: test

on:
  push:
    branches:
      - "*"

jobs:
    django-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3 # Checking out the repo

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d --system # Install all dependencies, including development ones

      - name: Django migrations
        run: mkdir db && \
             python django_lessons/manage.py makemigrations && \
             python django_lessons/manage.py migrate --run-syncdb

      - name: Install coverage
        run: python -m pip install coverage

      - name: Django Coverage action
        run: coverage run python django_lessons/manage.py test
