name: test

on:
  push:
    branches:
      - "*"

jobs:
    django-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3 # Checking out the repo

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: python -m pip install --upgrade pip && pip install pipenv
      
      - name: Install dependencies
        run: pipenv install -d 

      - name: Django migrations
        run: mkdir django_lessons/db && \
             python django_lessons/manage.py makemigrations && \
             python django_lessons/manage.py migrate --run-syncdb

      - name: Install coverage
        run: python -m pip install coverage

      - name: Django Coverage action
        run: coverage run python django_lessons/manage.py test
