name: test

on:
  push:
    branches:
      - "*"

jobs:
    django-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3 # Checking out the repo

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones

      - name: Django migrations
        run: mkdir db && pipenv run python manage.py makemigrations && pipenv run python manage.py migrate --run-syncdb

      - name: Django Coverage action
        uses: actions/python-django-coverage-gitHub-action@0.9
        with:
          django-app: 'django-lessons'
          minimum-coverage: '90'
