name: test

on:
  push:
    branches:
      - "*"

jobs:
    django-test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3 

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: python -m pip install --upgrade pip pipenv wheel 
      
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Django migrations
        run: | 
             mkdir django_lessons/db && \
             pipenv run python django_lessons/manage.py makemigrations && \
             pipenv run python django_lessons/manage.py migrate --run-syncdb

      - name: Install coverage
        run: pipenv install coverage

      - name: Django Coverage accounts tests
        run: pipenv run coverage run django_lessons/manage.py test accounts 

      - name: Django Coverage app tests
        run: pipenv run coverage run django_lessons/manage.py test app
      
      - name: Django Coverage chat tests
        run: pipenv run coverage run django_lessons/manage.py test chat
      
      - name: Django Coverage order tests
        run: pipenv run coverage run django_lessons/manage.py test order

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: .coverage
          retention-days: 1

    coverage:
        name: Coverage
        runs-on: ubuntu-latest
        needs: build
        steps:
          - uses: actions/checkout@v2

          - uses: actions/download-artifact@v2
            id: download
            with:
              name: test-coverage

          - name: Coverage comment
            id: coverage_comment
            uses: py-cov-action/python-coverage-comment-action@v3
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              MERGE_COVERAGE_FILES: true

          - name: Store Pull Request comment to be posted
            uses: actions/upload-artifact@v2
            if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
            with:
              name: python-coverage-comment-action
              path: python-coverage-comment-action.txt
